In [16]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'

# Make the API request
url = f"https://api.twelvedata.com/profile?symbol={symbol}&apikey={api_key}"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data = response.json()
    
    # Convert the dictionary to a pandas dataframe
    # Since the response is a single dictionary, we'll convert it to a dataframe by first turning it into a list
    df = pd.DataFrame([data])
    
    print(df)
else:
    print("Failed to retrieve data. Status code:", response.status_code)
df.columns

  symbol       name exchange mic_code      sector              industry  \
0   AAPL  Apple Inc   NASDAQ     XNGS  Technology  Consumer Electronics

   employees                website  \
0     161000  https://www.apple.com

                                         description          type  \
0  Apple Inc. designs, manufactures, and markets ...  Common Stock

                   CEO             address       city    zip state  \
0  Mr. Timothy D. Cook  One Apple Park Way  Cupertino  95014    CA

         country         phone
0  United States  408 996 1010

Index(['symbol', 'name', 'exchange', 'mic_code', 'sector', 'industry',
       'employees', 'website', 'description', 'type', 'CEO', 'address', 'city',
       'zip', 'state', 'country', 'phone'],
      dtype='object')

In [13]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'

# Make the API request for stock splits
url = f"https://api.twelvedata.com/splits?symbol={symbol}&apikey={api_key}&range=full"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data = response.json()
    
    # Extract the splits data
    splits_data = data.get('splits', [])
    
    # Convert the splits data to a pandas dataframe
    df_splits = pd.DataFrame(splits_data)
    
    # Display the dataframe
    print(df_splits)
else:
    print("Failed to retrieve data. Status code:", response.status_code)
df_splits.columns

         date    description    ratio  from_factor  to_factor
0  2020-08-31  4-for-1 split  0.25000            4          1
1  2014-06-09  7-for-1 split  0.14286            7          1
2  2005-02-28  2-for-1 split  0.50000            2          1
3  2000-06-21  2-for-1 split  0.50000            2          1
4  1987-06-16  2-for-1 split  0.50000            2          1

Index(['date', 'description', 'ratio', 'from_factor', 'to_factor'], dtype='object')

In [14]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'  # Note: API keys should be kept private and not shared in public code
symbol = 'AAPL'

# Make the API request for the income statement with quarterly data
url = f"https://api.twelvedata.com/income_statement?symbol={symbol}&apikey={api_key}&period=quarterly"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data = response.json()
    
    # Extract the income statement data
    income_statement_data = data.get('income_statement', [])
    
    # Flatten the data, including nested dictionaries for operating_expense and non_operating_interest
    flattened_data = []
    for item in income_statement_data:
        # Flatten nested dictionaries and combine with the rest of the item
        flattened_item = {**item, **item.get('operating_expense', {}), **item.get('non_operating_interest', {})}
        # Remove the original nested dictionaries
        flattened_item.pop('operating_expense', None)
        flattened_item.pop('non_operating_interest', None)
        flattened_data.append(flattened_item)
    
    # Convert the flattened data to a pandas dataframe
    df_income_statement = pd.DataFrame(flattened_data)
    
    # Optionally, sort the DataFrame by 'fiscal_date' if chronological order is desired
    df_income_statement.sort_values(by='fiscal_date', inplace=True)
    
    # Reset index after sorting
    df_income_statement.reset_index(drop=True, inplace=True)
    
    # Display the dataframe
    print(df_income_statement.head())  # Display the first few rows to check
else:
    print("Failed to retrieve data. Status code:", response.status_code)
df_income_statement.columns

  fiscal_date  quarter         sales  cost_of_goods  gross_profit  \
0  2022-12-31        1  117154000000    66822000000   50332000000
1  2023-03-31        2   94836000000    52860000000   41976000000
2  2023-06-30        3   81797000000    45384000000   36413000000
3  2023-09-30        4   89498000000    49071000000   40427000000
4  2023-12-31        1  119575000000    64720000000   54855000000

   operating_income  other_income_expense  pretax_income  income_tax  \
0       36016000000            -393000000    35623000000  5625000000
1       28318000000              76000000    28382000000  4222000000
2       22998000000            -247000000    22733000000  2852000000
3       26969000000              47000000    26998000000  4042000000
4       40373000000             -50000000    40323000000  6407000000

    net_income  ...         ebit       ebitda  \
0  29998000000  ...  36016000000  38932000000
1  24160000000  ...  29312000000  32210000000
2  19881000000  ...  23731000000  26783000000
3  22956000000  ...  28000000000  30653000000
4  33916000000  ...  40373000000  43221000000

   net_income_continuous_operations  minority_interests  \
0                       29998000000                None
1                       24160000000                None
2                       19881000000                None
3                       22956000000                None
4                       33916000000                None

   preferred_stock_dividends  research_and_development  \
0                       None                7709000000
1                       None                7457000000
2                       None                7442000000
3                       None                7307000000
4                       None                7696000000

   selling_general_and_administrative other_operating_expenses       income  \
0                          6607000000                     None  868000000.0
1                          6201000000                     None  918000000.0
2                          5973000000                     None  980000000.0
3                          6151000000                     None  984000000.0
4                          6786000000                     None          NaN

        expense
0  1.003000e+09
1  9.300000e+08
2  9.980000e+08
3  1.002000e+09
4           NaN

[5 rows x 24 columns]

Index(['fiscal_date', 'quarter', 'sales', 'cost_of_goods', 'gross_profit',
       'operating_income', 'other_income_expense', 'pretax_income',
       'income_tax', 'net_income', 'eps_basic', 'eps_diluted',
       'basic_shares_outstanding', 'diluted_shares_outstanding', 'ebit',
       'ebitda', 'net_income_continuous_operations', 'minority_interests',
       'preferred_stock_dividends', 'research_and_development',
       'selling_general_and_administrative', 'other_operating_expenses',
       'income', 'expense'],
      dtype='object')

In [15]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'
period = 'quarterly'  # Ensure the data is fetched by quarters

# Construct the API URL
url = f'https://api.twelvedata.com/cash_flow?symbol={symbol}&apikey={api_key}&period={period}'

# Make the API request
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a pandas DataFrame
    data = response.json()
    
    # Extract 'cash_flow' data
    cash_flow_data = data['cash_flow']
    
    # Normalize the data and create a DataFrame
    df_cash_flow = pd.json_normalize(cash_flow_data)
    
    # Add the 'meta' information as new columns if needed
    for key in data['meta']:
        df_cash_flow[key] = data['meta'][key]
    
    # Sort the DataFrame by 'fiscal_date' to ensure it's in chronological order
    df_cash_flow.sort_values(by='fiscal_date', inplace=True)
    
    # Reset index after sorting
    df_cash_flow.reset_index(drop=True, inplace=True)
    
    print(df_cash_flow.head())  # Display the first few rows of the DataFrame
else:
    print(f"Failed to fetch data: {response.status_code}")
df_cash_flow.columns

  fiscal_date  quarter  end_cash_position  income_tax_paid  interest_paid  \
0  2022-12-31        1        21974000000        828000000   7.030000e+08
1  2023-03-31        2        27129000000       4066000000   1.170000e+09
2  2023-06-30        3        29898000000       2126000000   7.170000e+08
3  2023-09-30        4        30737000000      11659000000   1.213000e+09
4  2023-12-31        1        41974000000       7255000000            NaN

   free_cash_flow  operating_activities.net_income  \
0     30218000000                      29998000000
1     25644000000                      24160000000
2     24287000000                      19881000000
3     19435000000                      22956000000
4     37503000000                      33916000000

   operating_activities.depreciation operating_activities.deferred_taxes  \
0                         2916000000                                None
1                         2898000000                                None
2                         3052000000                                None
3                         2653000000                                None
4                         2848000000                                None

   operating_activities.stock_based_compensation  ...  \
0                                     2905000000  ...
1                                     2686000000  ...
2                                     2617000000  ...
3                                     2625000000  ...
4                                     2997000000  ...

   financing_activities.common_dividends  \
0                            -3768000000
1                            -3650000000
2                            -3849000000
3                            -3758000000
4                            -3825000000

   financing_activities.other_financing_charges  \
0                                   -2705000000
1                                    -484000000
2                                   -2438000000
3                                    -385000000
4                                   -2637000000

   financing_activities.financing_cash_flow  symbol       name  currency  \
0                              -43777000000    AAPL  Apple Inc       USD
1                              -17510000000    AAPL  Apple Inc       USD
2                              -29276000000    AAPL  Apple Inc       USD
3                              -23153000000    AAPL  Apple Inc       USD
4                              -34569000000    AAPL  Apple Inc       USD

  exchange mic_code  exchange_timezone     period
0   NASDAQ     XNGS   America/New_York  Quarterly
1   NASDAQ     XNGS   America/New_York  Quarterly
2   NASDAQ     XNGS   America/New_York  Quarterly
3   NASDAQ     XNGS   America/New_York  Quarterly
4   NASDAQ     XNGS   America/New_York  Quarterly

[5 rows x 37 columns]

Index(['fiscal_date', 'quarter', 'end_cash_position', 'income_tax_paid',
       'interest_paid', 'free_cash_flow', 'operating_activities.net_income',
       'operating_activities.depreciation',
       'operating_activities.deferred_taxes',
       'operating_activities.stock_based_compensation',
       'operating_activities.other_non_cash_items',
       'operating_activities.accounts_receivable',
       'operating_activities.accounts_payable',
       'operating_activities.other_assets_liabilities',
       'operating_activities.operating_cash_flow',
       'investing_activities.capital_expenditures',
       'investing_activities.net_intangibles',
       'investing_activities.net_acquisitions',
       'investing_activities.purchase_of_investments',
       'investing_activities.sale_of_investments',
       'investing_activities.other_investing_activity',
       'investing_activities.investing_cash_flow',
       'financing_activities.long_term_debt_issuance',
       'financing_activities.long_term_debt_payments',
       'financing_activities.short_term_debt_issuance',
       'financing_activities.common_stock_issuance',
       'financing_activities.common_stock_repurchase',
       'financing_activities.common_dividends',
       'financing_activities.other_financing_charges',
       'financing_activities.financing_cash_flow', 'symbol', 'name',
       'currency', 'exchange', 'mic_code', 'exchange_timezone', 'period'],
      dtype='object')