In [ ]:
tickers = [
    "MSFT", "AAPL", "NVDA", "AMZN", "GOOGL", "META", "BRK.B", "LLY",
    "TSM", "AVGO", "TSLA", "V", "NVO", "JPM", "WMT", "UNH", "MA", "XOM",
    "ASML", "JNJ", "HD", "PG", "COST", "TM", "AMD", "MRK", "ABBV", "ORCL",
    "CRM", "CVX", "BAC", "NFLX", "ADBE", "KO", "ACN", "PEP", "FMX", "SAP",
    "TMO", "LIN", "MCD", "NVS", "ABT", "DIS", "SHEL", "AZN", "WFC", "CSCO",
    "TMUS", "DHR", "BABA", "INTU", "INTC", "QCOM", "AMAT", "GE", "IBM", "CMCSA",
    "VZ", "PDD", "UBER", "CAT", "AXP", "NOW", "TXN", "BX", "NKE", "UNP", "TTE",
    "AMGN", "PFE", "HSBC", "BHP", "MS", "LOW", "ISRG", "PM", "HDB", "RY", "SPGI",
    "COP", "SYK", "HON", "LRCX", "GS", "UPS", "PLD", "MUFG", "UL", "BA", "T",
    "BLK", "SCHW", "BUD", "BKNG", "RTX", "SNY", "ETN", "ELV", "NEE", "TJX", "VRTX",
    "MDT", "PGR", "SONY","FMC", "CIVI", "UI", "AZEK", "YMM", "RHP", "BZ", "TKO",
    "NYT", "GPS", "ALTR", "NFE", "XRAY", "CCCS", "SPSC", "STAG",
    "IVZ", "HAS", "DAR", "RMBS", "HQY", "RGLD", "ICL", "BILL",
    "VOYA", "CFR", "ITCI", "ENSG", "MAT", "FOUR", "GNRC", "THO",
    "BRX", "IBP", "WTS", "CGNX", "CHRD", "CACC", "AAON", "BERY",
    "MMYT", "LBTYK", "ALSN", "CBSH", "EXEL", "NOV", "ADT", "BFAM",
    "CRSP", "HRB", "MTZ", "MASI", "MTSI", "RLI", "DDS", "LSTR",
    "AGNC", "WFG", "STWD", "VNT", "IONS", "CAVA", "ANF", "OGE",
    "OLN", "CMA", "LYFT", "UGP", "AM", "VNOM", "CART", "ARW",
    "TNET", "CR", "SFM", "CSAN", "KVYO", "ATKR", "AN", "POST",
    "HXL", "VFC", "SIGI", "ATI", "BROS", "NOVT", "ALGM", "GTLS",
    "BBIO", "HLNE", "SSB", "FLR", "CMC", "KGC", "BYD", "PNFP",
    "WAL", "QLYS", "NE", "MUR", "NEU", "REYN", "WH", "NSIT",
    "TMHC", "CHX", "G", "GXO", "FAF", "ELP", "FRSH", "CAE",
    "MARA", "DRS", "BC", "ESAB", "MNSO", "BPOP", "LFUS", "WTFC",
    "ALTM", "TKR", "RRR", "GRFS", "OBDC", "CIGI", "RCM", "SMAR",
    "FYBR", "MLI", "GIL", "WHR", "FTAI", "OMF", "PBF", "BPMC",
    "PB", "BLCO", "MTH", "CIG", "ENLC", "ZION", "TRNO", "ESNT",
    "ESI", "ADC", "BRZE", "LANC", "TENB", "MSM","MXCT", "BALY", "SRI", "IVVD", "BWMN", "EQBK", "SD", "DJCO",
    "ATLC", "LSEA", "DENN", "SMBC", "GUTS", "ASLE", "CCBG", "VPG",
    "LWLG", "OFIX", "AEON", "LIND", "LND", "MTW", "CTLP", "RSVR",
    "ABUS", "AMNB", "NN", "LAND", "FPH", "HCAT", "ESPR", "JOUT",
    "ALNT", "RXT", "CATX", "GCBC", "ANNX", "RGP", "EGY", "TPB",
    "ZH", "VTRU", "DGICA", "CWCO", "RCEL", "CLFD", "DGICB", "AXGN",
    "ZIMV", "ALCC", "TRDA", "ADTN", "HONE", "CAC", "SRDX", "AVAH",
    "HAFC", "AURA", "STTK", "MCS", "TBPH", "TGB", "KODK", "TERN",
    "HTBI", "MGX", "NTGR", "NFBK", "TRC", "BETR", "ORC", "GDEV",
    "URG", "RDZN", "WTI", "PNNT", "GHRS", "GATO", "EHAB", "GLAD",
    "TSAT", "MED", "BBCP", "BLZE", "CELC", "XERS", "SVM", "MVIS",
    "WASH", "GLRE", "IVR", "AVNW", "ANSC", "OCS", "OSG", "DHIL",
    "EAF", "THFF", "CVRX", "SLAM", "AVXL", "AMRN", "CRMT", "FFWM",
    "DCGO", "OLP", "AUDC", "ALRS", "BTMD", "GDOT", "NYXH", "SPFI",
    "FBLG", "ACRE", "PGC", "CLOV", "CCG", "DOMO", "MCB", "PGEN",
    "NPCE", "ONEW", "NVEC", "EPIX", "LYTS", "FARO", "TMC", "GFR",
    "ESQ", "THRD", "CCNE", "PBPB", "NBN", "STRW", "FSBC", "BHRB",
    "LXEO", "IAUX", "LAW", "MGTX", "RMR", "NGNE", "AROW", "GBLI",
    "ACTG", "INZY", "ITOS", "STEM", "ARMN", "MODV", "NCMI", "ANRO",
    "NETD", "VALU", "HRZN", "OPY", "VNET", "SGU", "ZYXI", "OSPN"
]

In [ ]:
import requests
import json

# Your Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'

# The URL for the stocks endpoint
url = 'https://api.twelvedata.com/stocks'

# Parameters for the API request
params = {
    'apikey': api_key
}

# Make the GET request to the Twelve Data API
response = requests.get(url, params=params)

# Initialize a counter for numbering the US stocks
counter = 1

# Check if the request was successful
if response.status_code == 200:
    # Convert the response to JSON
    data = response.json()
    
    # Check if 'data' key is in response (as expected format)
    if 'data' in data:
        # Loop through each stock in the response
        for stock in data['data']:
            # Check if the stock is from the United States
            if stock.get('country') == 'United States':
                # Print the numbered list of US stocks
                print(f"{counter}. Symbol: {stock['symbol']}, Name: {stock['name']}, Currency: {stock['currency']}, Exchange: {stock['exchange']}, Country: {stock['country']}, Type: {stock['type']}")
                # Increment the counter
                counter += 1
    else:
        # If 'data' key is not in response, print the whole response (for debugging)
        print(json.dumps(data, indent=4))
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}, Response: {response.text}")

In [ ]:
import requests
import random

# Your Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'

# The URL for the stocks endpoint
url = 'https://api.twelvedata.com/stocks'

# Parameters for the API request
params = {
    'apikey': api_key
}

# Your list of stocks to exclude
exclude_stocks = [
       "MSFT", "AAPL", "NVDA", "AMZN", "GOOGL", "META", "BRK.B", "LLY",
    "TSM", "AVGO", "TSLA", "V", "NVO", "JPM", "WMT", "UNH", "MA", "XOM",
    "ASML", "JNJ", "HD", "PG", "COST", "TM", "AMD", "MRK", "ABBV", "ORCL",
    "CRM", "CVX", "BAC", "NFLX", "ADBE", "KO", "ACN", "PEP", "FMX", "SAP",
    "TMO", "LIN", "MCD", "NVS", "ABT", "DIS", "SHEL", "AZN", "WFC", "CSCO",
    "TMUS", "DHR", "BABA", "INTU", "INTC", "QCOM", "AMAT", "GE", "IBM", "CMCSA",
    "VZ", "PDD", "UBER", "CAT", "AXP", "NOW", "TXN", "BX", "NKE", "UNP", "TTE",
    "AMGN", "PFE", "HSBC", "BHP", "MS", "LOW", "ISRG", "PM", "HDB", "RY", "SPGI",
    "COP", "SYK", "HON", "LRCX", "GS", "UPS", "PLD", "MUFG", "UL", "BA", "T",
    "BLK", "SCHW", "BUD", "BKNG", "RTX", "SNY", "ETN", "ELV", "NEE", "TJX", "VRTX",
    "MDT", "PGR", "SONY","FMC", "CIVI", "UI", "AZEK", "YMM", "RHP", "BZ", "TKO",
    "NYT", "GPS", "ALTR", "NFE", "XRAY", "CCCS", "SPSC", "STAG",
    "IVZ", "HAS", "DAR", "RMBS", "HQY", "RGLD", "ICL", "BILL",
    "VOYA", "CFR", "ITCI", "ENSG", "MAT", "FOUR", "GNRC", "THO",
    "BRX", "IBP", "WTS", "CGNX", "CHRD", "CACC", "AAON", "BERY",
    "MMYT", "LBTYK", "ALSN", "CBSH", "EXEL", "NOV", "ADT", "BFAM",
    "CRSP", "HRB", "MTZ", "MASI", "MTSI", "RLI", "DDS", "LSTR",
    "AGNC", "WFG", "STWD", "VNT", "IONS", "CAVA", "ANF", "OGE",
    "OLN", "CMA", "LYFT", "UGP", "AM", "VNOM", "CART", "ARW",
    "TNET", "CR", "SFM", "CSAN", "KVYO", "ATKR", "AN", "POST",
    "HXL", "VFC", "SIGI", "ATI", "BROS", "NOVT", "ALGM", "GTLS",
    "BBIO", "HLNE", "SSB", "FLR", "CMC", "KGC", "BYD", "PNFP",
    "WAL", "QLYS", "NE", "MUR", "NEU", "REYN", "WH", "NSIT",
    "TMHC", "CHX", "G", "GXO", "FAF", "ELP", "FRSH", "CAE",
    "MARA", "DRS", "BC", "ESAB", "MNSO", "BPOP", "LFUS", "WTFC",
    "ALTM", "TKR", "RRR", "GRFS", "OBDC", "CIGI", "RCM", "SMAR",
    "FYBR", "MLI", "GIL", "WHR", "FTAI", "OMF", "PBF", "BPMC",
    "PB", "BLCO", "MTH", "CIG", "ENLC", "ZION", "TRNO", "ESNT",
    "ESI", "ADC", "BRZE", "LANC", "TENB", "MSM","MXCT", "BALY", "SRI", "IVVD", "BWMN", "EQBK", "SD", "DJCO",
    "ATLC", "LSEA", "DENN", "SMBC", "GUTS", "ASLE", "CCBG", "VPG",
    "LWLG", "OFIX", "AEON", "LIND", "LND", "MTW", "CTLP", "RSVR",
    "ABUS", "AMNB", "NN", "LAND", "FPH", "HCAT", "ESPR", "JOUT",
    "ALNT", "RXT", "CATX", "GCBC", "ANNX", "RGP", "EGY", "TPB",
    "ZH", "VTRU", "DGICA", "CWCO", "RCEL", "CLFD", "DGICB", "AXGN",
    "ZIMV", "ALCC", "TRDA", "ADTN", "HONE", "CAC", "SRDX", "AVAH",
    "HAFC", "AURA", "STTK", "MCS", "TBPH", "TGB", "KODK", "TERN",
    "HTBI", "MGX", "NTGR", "NFBK", "TRC", "BETR", "ORC", "GDEV",
    "URG", "RDZN", "WTI", "PNNT", "GHRS", "GATO", "EHAB", "GLAD",
    "TSAT", "MED", "BBCP", "BLZE", "CELC", "XERS", "SVM", "MVIS",
    "WASH", "GLRE", "IVR", "AVNW", "ANSC", "OCS", "OSG", "DHIL",
    "EAF", "THFF", "CVRX", "SLAM", "AVXL", "AMRN", "CRMT", "FFWM",
    "DCGO", "OLP", "AUDC", "ALRS", "BTMD", "GDOT", "NYXH", "SPFI",
    "FBLG", "ACRE", "PGC", "CLOV", "CCG", "DOMO", "MCB", "PGEN",
    "NPCE", "ONEW", "NVEC", "EPIX", "LYTS", "FARO", "TMC", "GFR",
    "ESQ", "THRD", "CCNE", "PBPB", "NBN", "STRW", "FSBC", "BHRB",
    "LXEO", "IAUX", "LAW", "MGTX", "RMR", "NGNE", "AROW", "GBLI",
    "ACTG", "INZY", "ITOS", "STEM", "ARMN", "MODV", "NCMI", "ANRO",
    "NETD", "VALU", "HRZN", "OPY", "VNET", "SGU", "ZYXI", "OSPN"
]

# Make the GET request to the Twelve Data API
response = requests.get(url, params=params)

# Initialize a list to hold all available stocks from Twelve Data
all_stocks = []

# Check if the request was successful
if response.status_code == 200:
    # Convert the response to JSON
    data = response.json()
    
    # Ensure the 'data' key is in the response
    if 'data' in data:
        # Loop through each stock in the response
        for stock in data['data']:
            # Add the stock symbol to the list of all stocks
            all_stocks.append(stock['symbol'])

    # Filter out the stocks from the exclude list
    filtered_stocks = [stock for stock in all_stocks if stock not in exclude_stocks]
    
    # Select 500 random stocks from the filtered list
    # Ensure the list has enough elements to avoid ValueError
    if len(filtered_stocks) >= 500:
        random_stocks = random.sample(filtered_stocks, 500)
        print("500 random stocks not in the exclude list:")
        for i, stock in enumerate(random_stocks, start=1):
            print(f"{i}. {stock}")
    else:
        print("Not enough stocks available to select 500 unique stocks after filtering.")
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}, Response: {response.text}")

In [ ]:
for item in random_stocks:
    tickers.append(item)
len(tickers)

In [16]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'

# Make the API request
url = f"https://api.twelvedata.com/profile?symbol={symbol}&apikey={api_key}"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data = response.json()
    
    # Convert the dictionary to a pandas dataframe
    # Since the response is a single dictionary, we'll convert it to a dataframe by first turning it into a list
    df = pd.DataFrame([data])
    
    print(df)
else:
    print("Failed to retrieve data. Status code:", response.status_code)
df.columns

  symbol       name exchange mic_code      sector              industry  \
0   AAPL  Apple Inc   NASDAQ     XNGS  Technology  Consumer Electronics

   employees                website  \
0     161000  https://www.apple.com

                                         description          type  \
0  Apple Inc. designs, manufactures, and markets ...  Common Stock

                   CEO             address       city    zip state  \
0  Mr. Timothy D. Cook  One Apple Park Way  Cupertino  95014    CA

         country         phone
0  United States  408 996 1010

Index(['symbol', 'name', 'exchange', 'mic_code', 'sector', 'industry',
       'employees', 'website', 'description', 'type', 'CEO', 'address', 'city',
       'zip', 'state', 'country', 'phone'],
      dtype='object')

In [45]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'

# Make the API request for stock splits
url = f"https://api.twelvedata.com/splits?symbol={symbol}&apikey={api_key}&range=full"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data = response.json()
    
    # Extract the splits data
    splits_data = data.get('splits', [])
    
    # Convert the splits data to a pandas dataframe
    df_splits = pd.DataFrame(splits_data)
    
    # Display the dataframe
    print(df_splits)
else:
    print("Failed to retrieve data. Status code:", response.status_code)
df_splits.columns

         date    description    ratio  from_factor  to_factor
0  2020-08-31  4-for-1 split  0.25000            4          1
1  2014-06-09  7-for-1 split  0.14286            7          1
2  2005-02-28  2-for-1 split  0.50000            2          1
3  2000-06-21  2-for-1 split  0.50000            2          1
4  1987-06-16  2-for-1 split  0.50000            2          1

Index(['date', 'description', 'ratio', 'from_factor', 'to_factor'], dtype='object')

In [46]:
len(tickers)

915

915

income statement quarterly

In [52]:
import requests
import pandas as pd
import time
import os

# API Key should be kept private
api_key = '3cc2c2885bea431abf95d6f776acc139'

csv_file_name = 'income_statements.csv'


write_header = not os.path.exists(csv_file_name)

# Iterate over each ticker symbol
for symbol in tickers:
    print(f"Processing {symbol}...")
    url = f"https://api.twelvedata.com/income_statement?symbol={symbol}&apikey={api_key}&period=quarterly"
    response = requests.get(url)
    
    # Check if the request was successful
    if response.status_code == 200 and response.json().get('status') != 'error':
        data = response.json()
        
        # Extract and flatten the income statement data
        income_statement_data = data.get('income_statement', [])
        flattened_data = []
        for item in income_statement_data:
            flattened_item = {**item, **item.get('operating_expense', {}), **item.get('non_operating_interest', {})}
            flattened_item.pop('operating_expense', None)
            flattened_item.pop('non_operating_interest', None)
            flattened_data.append(flattened_item)
        
        # Convert the flattened data to a DataFrame
        df_income_statement = pd.DataFrame(flattened_data)
        df_income_statement['ticker'] = symbol
        # Append DataFrame to the CSV file
        df_income_statement.to_csv(csv_file_name, mode='a', index=False, header=write_header)
        
        # Ensure the header is not written again in subsequent writes
        write_header = False
        
        print(f"Data for {symbol} added to {csv_file_name}.")
    else:
        print(f"No data for {symbol} or failed to retrieve data. Status code: {response.status_code}")
    
    # Wait for 12 seconds before processing the next ticker
    time.sleep(12)

print("All requested data processed.")

Processing MSFT...
Data for MSFT added to income_statements.csv.
Processing AAPL...
Data for AAPL added to income_statements.csv.
Processing NVDA...
Data for NVDA added to income_statements.csv.

income statement yearly

In [29]:
import requests
import pandas as pd
from datetime import datetime, timedelta

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'  # Remember to keep your API keys private
symbol = 'AAPL'

# Calculate the start date as 5 years back from today
start_date = (datetime.now() - timedelta(days=10*365)).strftime('%Y-%m-%d')

# Make the API request for the income statement with quarterly data, including the start date
url = f"https://api.twelvedata.com/income_statement?symbol={symbol}&apikey={api_key}&period=annual"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    
    # Extract the income statement data
    income_statement_data = data.get('income_statement', [])
    
    # Process the data
    flattened_data = []
    for item in income_statement_data:
        flattened_item = {**item, **item.get('operating_expense', {}), **item.get('non_operating_interest', {})}
        flattened_item.pop('operating_expense', None)
        flattened_item.pop('non_operating_interest', None)
        flattened_data.append(flattened_item)
    
    df_income_statement = pd.DataFrame(flattened_data)
    
    # Sorting and resetting index
    df_income_statement.sort_values(by='fiscal_date', inplace=True)
    df_income_statement.reset_index(drop=True, inplace=True)
    
    print(df_income_statement)
else:
    print("Failed to retrieve data. Status code:", response.status_code)

# Check how many rows were retrieved to estimate the coverage
print(f"Retrieved {len(df_income_statement)} rows of data.")

  fiscal_date         sales  cost_of_goods  gross_profit  operating_income  \
0  2020-09-30  274515000000   169559000000  104956000000       66288000000
1  2021-09-30  365817000000   212981000000  152836000000      108949000000
2  2022-09-30  394328000000   223546000000  170782000000      119437000000
3  2023-09-30  383285000000   214137000000  169148000000      114301000000

   other_income_expense  pretax_income   income_tax   net_income  eps_basic  \
0             -87000000    67091000000   9680000000  57411000000       3.31
1              60000000   109207000000  14527000000  94680000000       5.67
2            -228000000   119103000000  19300000000  99803000000       6.15
3            -382000000   113736000000  16741000000  96995000000       6.16

   ...          ebit        ebitda  net_income_continuous_operations  \
0  ...   69964000000   81020000000                       57411000000
1  ...  111852000000  123136000000                       94680000000
2  ...  122034000000  133138000000                       99803000000
3  ...  117669000000  129188000000                       96995000000

   minority_interests  preferred_stock_dividends  research_and_development  \
0                None                       None               18752000000
1                None                       None               21914000000
2                None                       None               26251000000
3                None                       None               29915000000

  selling_general_and_administrative other_operating_expenses      income  \
0                        19916000000                     None  3763000000
1                        21973000000                     None  2843000000
2                        25094000000                     None  2825000000
3                        24932000000                     None  3750000000

      expense
0  2873000000
1  2645000000
2  2931000000
3  3933000000

[4 rows x 23 columns]
Retrieved 4 rows of data.

In [12]:
import requests
import pandas as pd

# Replace 'your_api_key' with your actual Twelve Data API key
api_key = '3cc2c2885bea431abf95d6f776acc139'
symbol = 'AAPL'
period = 'quarterly'  # Ensure the data is fetched by quarters

# Construct the API URL
url = f'https://api.twelvedata.com/cash_flow?symbol={symbol}&apikey={api_key}&period={period}'

# Make the API request
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a pandas DataFrame
    data = response.json()
    
    # Extract 'cash_flow' data
    cash_flow_data = data['cash_flow']
    
    # Normalize the data and create a DataFrame
    df_cash_flow = pd.json_normalize(cash_flow_data)
    
    # Add the 'meta' information as new columns if needed
    for key in data['meta']:
        df_cash_flow[key] = data['meta'][key]
    
    # Sort the DataFrame by 'fiscal_date' to ensure it's in chronological order
    df_cash_flow.sort_values(by='fiscal_date', inplace=True)
    
    # Reset index after sorting
    df_cash_flow.reset_index(drop=True, inplace=True)
    
    print(df_cash_flow.head())  # Display the first few rows of the DataFrame
else:
    print(f"Failed to fetch data: {response.status_code}")
df_cash_flow.columns

  fiscal_date  quarter  end_cash_position  income_tax_paid  interest_paid  \
0  2022-12-31        1        21974000000        828000000   7.030000e+08
1  2023-03-31        2        27129000000       4066000000   1.170000e+09
2  2023-06-30        3        29898000000       2126000000   7.170000e+08
3  2023-09-30        4        30737000000      11659000000   1.213000e+09
4  2023-12-31        1        41974000000       7255000000            NaN

   free_cash_flow  operating_activities.net_income  \
0     30218000000                      29998000000
1     25644000000                      24160000000
2     24287000000                      19881000000
3     19435000000                      22956000000
4     37503000000                      33916000000

   operating_activities.depreciation operating_activities.deferred_taxes  \
0                         2916000000                                None
1                         2898000000                                None
2                         3052000000                                None
3                         2653000000                                None
4                         2848000000                                None

   operating_activities.stock_based_compensation  ...  \
0                                     2905000000  ...
1                                     2686000000  ...
2                                     2617000000  ...
3                                     2625000000  ...
4                                     2997000000  ...

   financing_activities.common_dividends  \
0                            -3768000000
1                            -3650000000
2                            -3849000000
3                            -3758000000
4                            -3825000000

   financing_activities.other_financing_charges  \
0                                   -2705000000
1                                    -484000000
2                                   -2438000000
3                                    -385000000
4                                   -2637000000

   financing_activities.financing_cash_flow  symbol       name  currency  \
0                              -43777000000    AAPL  Apple Inc       USD
1                              -17510000000    AAPL  Apple Inc       USD
2                              -29276000000    AAPL  Apple Inc       USD
3                              -23153000000    AAPL  Apple Inc       USD
4                              -34569000000    AAPL  Apple Inc       USD

  exchange mic_code  exchange_timezone     period
0   NASDAQ     XNGS   America/New_York  Quarterly
1   NASDAQ     XNGS   America/New_York  Quarterly
2   NASDAQ     XNGS   America/New_York  Quarterly
3   NASDAQ     XNGS   America/New_York  Quarterly
4   NASDAQ     XNGS   America/New_York  Quarterly

[5 rows x 37 columns]

Index(['fiscal_date', 'quarter', 'end_cash_position', 'income_tax_paid',
       'interest_paid', 'free_cash_flow', 'operating_activities.net_income',
       'operating_activities.depreciation',
       'operating_activities.deferred_taxes',
       'operating_activities.stock_based_compensation',
       'operating_activities.other_non_cash_items',
       'operating_activities.accounts_receivable',
       'operating_activities.accounts_payable',
       'operating_activities.other_assets_liabilities',
       'operating_activities.operating_cash_flow',
       'investing_activities.capital_expenditures',
       'investing_activities.net_intangibles',
       'investing_activities.net_acquisitions',
       'investing_activities.purchase_of_investments',
       'investing_activities.sale_of_investments',
       'investing_activities.other_investing_activity',
       'investing_activities.investing_cash_flow',
       'financing_activities.long_term_debt_issuance',
       'financing_activities.long_term_debt_payments',
       'financing_activities.short_term_debt_issuance',
       'financing_activities.common_stock_issuance',
       'financing_activities.common_stock_repurchase',
       'financing_activities.common_dividends',
       'financing_activities.other_financing_charges',
       'financing_activities.financing_cash_flow', 'symbol', 'name',
       'currency', 'exchange', 'mic_code', 'exchange_timezone', 'period'],
      dtype='object')